version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: app_container
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    volumes:
      - .:/app

volumes:
  mongo_data:
